# Generated by Django 3.2.6 on 2021-09-11 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name': 'Ausbildungsrichtung', 'verbose_name_plural': 'Ausbildungsrichtungen'},
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'verbose_name': 'Jahrgangsstufe', 'verbose_name_plural': 'Jahrgangsstufen'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Aufgabe', 'verbose_name_plural': 'Aufgaben'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'Lernbereich', 'verbose_name_plural': 'Lernbereiche'},
        ),
    ]
