# Generated by Django 3.2.6 on 2021-09-11 11:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_organization', '0002_auto_20210911_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(max_length=500, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='task',
            name='headline',
            field=models.CharField(max_length=100, verbose_name='Überschrift'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_text',
            field=models.TextField(blank=True, null=True, verbose_name='Aufgabentext'),
        ),
        migrations.AlterField(
            model_name='task',
            name='topic',
            field=models.ManyToManyField(to='exam_organization.Topic', verbose_name='Lernbereiche'),
        ),
        migrations.AlterField(
            model_name='task',
            name='total_BE',
            field=models.CharField(blank=True, help_text='Pro Teilaufgabe, getrennt durch Kommata', max_length=50, validators=[django.core.validators.int_list_validator], verbose_name='Bewertungseinheiten'),
        ),
    ]
