# Generated by Django 3.2.6 on 2021-09-13 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_organization', '0003_auto_20210911_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='topic',
            field=models.ManyToManyField(blank=True, null=True, to='exam_organization.Topic', verbose_name='Lernbereiche'),
        ),
    ]
