# Generated by Django 3.2.6 on 2021-09-13 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_organization', '0004_alter_task_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='topic',
            field=models.ManyToManyField(blank=True, to='exam_organization.Topic', verbose_name='Lernbereiche'),
        ),
    ]
